require("config.keymaps")
require("config.packer")
require("config.telescope")
require("config.colorscheme")
require("config.treesitter")
require("config.lsp")
require("config.options")
require("config.nvim-tree")
require("config.autopairs")
require("config.toggleterm")
require("config.comments")

