#!/usr/bin/bash

status=$(bluetoothctl show | grep Powered | awk -F ': ' '{print $2}')

if [ $status == "yes" ]
then
    bluetoothctl power off
    kill -41 $(pidof dwmblocks)
else
    bluetoothctl power on && bluetoothctl scan on
    kill -41 $(pidof dwmblocks)
fi


