#!/usr/bin/bash

max_bright=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if [[ $brightness -lt $max_bright ]]
then
    brightness=$(($brightness+1000))
    echo $brightness > /sys/class/backlight/intel_backlight/brightness
fi

