#!/usr/bin/bash

notDam=$(ps -auxc | grep "notification" | wc -l) 

[[ $notDam -eq 1 ]] && killall notification-daemon
kill -44 $(pidof dwmblocks)
notify-send -u low $(amixer get Master | grep -i "left:" | grep -oP "\\d+%")

